CC=g++
LIB_PATH="/home/mianvi/libs/boost_1_86_0"

all: main.cpp
	$(CC) -I $(LIB_PATH) main.cpp -o main

server: server.cpp
	$(CC) -I $(LIB_PATH) server.cpp -o server

client: client.cpp
	$(CC) -I $(LIB_PATH) client.cpp -o client
